In [1]:
import numpy as np

In [45]:
from IPython.display import display

In [2]:
[0,1,2,3]

[0, 1, 2, 3]

In [4]:
np.array([0,1,2,3]).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [7]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.arange(100).reshape(10,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
sudoku = np.zeros((9,9))

In [52]:
sudoku = np.random.randint(1,high=10,size=(9,9))

In [53]:
sudoku

array([[7, 9, 6, 8, 8, 4, 3, 3, 3],
       [8, 2, 7, 6, 2, 4, 4, 7, 6],
       [5, 1, 9, 2, 2, 2, 7, 6, 2],
       [2, 3, 6, 8, 8, 7, 2, 4, 5],
       [7, 3, 8, 5, 5, 8, 3, 2, 4],
       [9, 7, 8, 2, 7, 2, 3, 4, 8],
       [9, 1, 1, 1, 1, 3, 9, 2, 8],
       [7, 2, 4, 4, 5, 7, 7, 9, 5],
       [1, 8, 2, 1, 7, 3, 7, 3, 4]])

In [79]:
def bigger_zero(array):
    count = np.bincount(array)
    return np.arange(10)[np.bincount(array)>0], count[np.bincount(array)>0]
def smaller_one(array):
    count = np.bincount(array)
    return np.arange(10)[np.bincount(array)<1], count[np.bincount(array)<1]

In [80]:
bigger_zero(sudoku[0,])

(array([3, 4, 6, 7, 8, 9]), array([3, 1, 1, 1, 2, 1]))

In [81]:
smaller_zero(sudoku[0,])

(array([], dtype=int64), array([3, 1, 1, 1, 2, 1]))

In [57]:
sudoku[0,]

array([7, 9, 6, 8, 8, 4, 3, 3, 3])

In [46]:
x = 0
y = 1
for x in [0,1,2]:
    for y in [0,1,2]:
        display(sudoku[x*3:x*3+3, y*3:y*3+3])

array([[5, 8, 9],
       [0, 0, 5],
       [6, 2, 8]])

array([[2, 8, 9],
       [5, 0, 4],
       [7, 6, 2]])

array([[9, 0, 3],
       [8, 3, 6],
       [4, 4, 1]])

array([[1, 9, 1],
       [3, 1, 4],
       [4, 4, 0]])

array([[2, 3, 0],
       [2, 3, 9],
       [4, 2, 6]])

array([[9, 3, 3],
       [3, 3, 7],
       [9, 0, 2]])

array([[8, 8, 8],
       [1, 6, 5],
       [5, 7, 6]])

array([[8, 3, 6],
       [7, 1, 3],
       [4, 2, 8]])

array([[8, 6, 3],
       [7, 3, 1],
       [2, 0, 1]])

In [24]:
sudoku[0,0] = 5

In [27]:
sudoku[5,-5:]

array([2, 6, 9, 0, 2])

In [36]:
i = 3
sudoku[0:i, 0:i]

array([[5, 8, 9],
       [0, 0, 5],
       [6, 2, 8]])

In [37]:
i = 3
sudoku[3:6, 0:3]

array([[1, 9, 1],
       [3, 1, 4],
       [4, 4, 0]])

In [38]:
i = 3
sudoku[6:, 0:3]

array([[8, 8, 8],
       [1, 6, 5],
       [5, 7, 6]])

In [43]:
x = 0
y = 1
sudoku[x*3:x*3+3, y*3:y*3+3]

array([[2, 8, 9],
       [5, 0, 4],
       [7, 6, 2]])

In [91]:
sudoku = np.zeros((9,9), dtype=int)

In [122]:
sudoku = np.zeros((4,4))

In [127]:
sudoku

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  3.,  4.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [124]:
sudoku[0] = np.arange(1,5)

In [126]:
sudoku[1] = np.append(np.arange(1,5)[1:], np.arange(1,5)[0])

In [117]:
sudoku

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9, 1],
       [3, 4, 5, 6, 7, 8, 9, 1, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [94]:
sudoku[0] = np.arange(1,10)

In [115]:
sudoku[1] = np.append(np.arange(1,10)[1:], np.arange(1,10)[0])

In [116]:
sudoku[2] = np.append(np.arange(1,10)[2:], np.arange(1,10)[:2])

In [110]:
np.append(np.arange(1,10)[1:], np.arange(1,10)[0])

array([2, 3, 4, 5, 6, 7, 8, 9, 1])

In [108]:
np.arange(1,10)[0]

1

In [109]:
np.concatenate(np.arange(1,10)[1:], np.array([np.arange(1,10)[0]]))

TypeError: only integer scalar arrays can be converted to a scalar index

In [105]:
np.array([1,2,3])+np.array([1])

array([2, 3, 4])

In [84]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
np.arange(1,10).reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])